apiVersion: v1
kind: Pod
metadata:
  name: paymentservice
spec:
  containers:
    - name: paymentservice
      image: equationalapplications/paymentservice:0.0.1

---
apiVersion: v1
kind: Service
metadata:
  name: paymentservice-clusterip
spec:
  selector:
    app: paymentservice
  ports:
    - name: paymentservice
      protocol: TCP
      port: 8081
      targetPort: 8081