export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FAIL = "USER_LOGIN_FAIL";
export const USER_LOGOUT = "USER_LOGOUT";

export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS  = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FAIL ="USER_REGISTER_FAIL";

export const SELLER_LOGIN_FAIL = " SELLER_LOGIN_FAIL";
export const SELLER_LOGIN_REQUEST ="SELLER_LOGIN_REQUEST";
export const SELLER_LOGIN_SUCCESS ="SELLER_LOGIN_SUCCESS ";
export const SELLER_LOGOUT = "SELLER_LOGOUT";